server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
        - AddResponseHeader=X-Gateway, api-gateway
      routes:
        # Hotels API
        - id: hotels
          uri: lb://hotels
          predicates:
            - Path=/api/hotels/**, /api/rooms/**        # если проксируешь и rooms
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1

        # Auth эндпойнты Booking: /api/bookings/user/** -> /user/**
        - id: booking-auth
          uri: lb://booking
          predicates:
            - Path=/api/bookings/user/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=2

        # Остальные Booking ручки: /api/bookings/** -> /**
        - id: booking
          uri: lb://booking
          predicates:
            - Path=/api/bookings/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: booking
        url: /api/bookings/v3/api-docs
      - name: hotels
        url: /api/hotels/v3/api-docs

security:
  jwt:
    secret: "dev-super-secret-change-me-32-bytes-minimum!!!"
